app:
  name: webnest
  image:
    repository: dsegura97/pokeapinest
    tag: latest
    pullPolicy: Always
  # containerPort: 3001   
  container: 
    name: webnest
    port: 3001
    replicas: 3
  service:
    type: NodePort
    port: 3001
    nodePort: 30022
    sshPort: 3456
    sshTargetPort: 3456
    sshNodePort: 30456
  ingress:
    host: nesthelm.davidsegurarodriguez.es
    port: 3001

postgres:
  name: postgre
  image:
    repository: dsegura97/postgre
    tag: "latest"
    pullPolicy: Always
  service:
    port: 5432
  auth:
    database: pokenest
    username: postgres
    password: usuario
  # Este es el volumen donde se guardarán los datos de PostgreSQL. Si quieres usar un volumen persistente
  persistence:
    enabled: true
    size: 1Gi
    storageClassName: "microk8s-hostpath"   # pon aquí tu storageClass si quieres fijarla