services:
  web:
    build:
      context: /home/david/kube/docker/kube
      dockerfile: ./dockerfiles/nodejs/node
    container_name: ctdavidbase
    ports:
      - "2456:22"
    env_file:
      - ./.env
    image: dsegura97/ubbase
    volumes:
      - ./logs:/root/logs
    networks:
      netnode:
        ipv4_address: 172.130.13.4
networks:
  netnode:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.130.13.0/24
