services:
  web:
    build:
      context: /home/david/kube/docker/kube
      dockerfile: ./dockerfiles/postgre/postgre
    container_name: ctdavidpostgre
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    image: dsegura97/postgre
    volumes:
      - ./logs:/root/logs
    networks:
      netpostgre:
        ipv4_address: 172.130.17.4
networks:
  netpostgre:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.130.17.0/24
