services:
  web:
    build:
      context: /home/david/kube/docker/kube
      dockerfile: ./dockerfiles/pokeapinest/pokeapinest
    container_name: ctdavidnestpokeapi
    image: dsegura97/pokeapinest
    ports:
      - 3010:3001
    env_file:
      - ./.env
    volumes:
      - ./logs:/root/logs
