services:
  web:
    build:
      context: /home/david/kube/docker/kube
      dockerfile: ./dockerfiles/seguridad/seguridad
    container_name: ctdavidseguridad
    env_file:
      - ./.env
    image: dsegura97/ubseguridad
    volumes:
      - ./logs:/root/logs

