apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.postgres.name }}-configmap
  namespace: {{ .Release.Namespace }}
data:
  POSTGRES_HOST: {{ .Values.postgres.name }}
  POSTGRES_PORT: {{ .Values.postgres.service.port | quote }}
  POSTGRES_DB: {{ .Values.postgres.auth.database }}
