apiVersion: v1
kind: Service
metadata:
  name: nest-taller
  namespace: pokeapi-nest
spec:
  type: NodePort
  selector:
    app: webnest
  ports:
    - name: http
      port: 3001
      targetPort: 3001
    - name: ssh
      port: 22452
      targetPort: 22452
      nodePort: 30022