apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.container.name }}-service
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.app.service.type }}
  selector:
    app: {{ .Values.app.container.name }}
  ports:
    - name: http
      port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.container.port }}
      nodePort: {{ .Values.app.service.nodePort }}
    - name: ssh
      port: {{ .Values.app.service.sshPort }}
      targetPort: {{ .Values.app.service.sshPort }}
      nodePort: {{ .Values.app.service.sshNodePort }}