services:
  web:
    build:
      context: /home/david/kube/docker/kube
      dockerfile: ./dockerfiles/sweb/nginx/nginxbase
    container_name: ctdavinginx
    env_file:
      - ./.env
    image: dsegura97/nginx
    volumes:
      - ./logs:/root/logs
