apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre-deployment
  namespace: pokeapi-nest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
      - name: postgre
        image: dsegura97/postgre
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgre-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgre-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgre-secret
              key: POSTGRES_DB
        volumeMounts:
        - name: postgre-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgre-storage
        persistentVolumeClaim:
          claimName: postgre-pvc