apiVersion: v1
kind: Secret
metadata:
  name: postgre-secret
  namespace: pokeapi-nest
type: Opaque
data:
  # "postgres" en base64
  POSTGRES_USER: postgres
  # "usuario" en base64
  POSTGRES_PASSWORD: usuario
  # "pokenest" en base64
  POSTGRES_DB: pokenest