services:
  web:
    build:
      context: /home/david/kube/docker/kube
      dockerfile: ./dockerfiles/nodejsnest/node
    container_name: ctdavidnest
    ports:
      - "3000:80"
    env_file:
      - ./.env
    image: dsegura97/nestjs
    volumes:
      - ./logs:/root/logs
